# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # bolt-sidecar: breaking major and pre v1 updates
  - package-ecosystem: "cargo"
    directory: "/bolt-sidecar"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: ">=1.0.0"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # bolt-sidecar: non-breaking minor and patch updates
  - package-ecosystem: "cargo"
    directory: "/bolt-sidecar"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: "<1.0.0"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # bolt-cli: breaking major and pre v1 updates
  - package-ecosystem: "cargo"
    directory: "/bolt-cli"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: ">=1.0.0"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # bolt-cli: non-breaking minor and patch updates
  - package-ecosystem: "cargo"
    directory: "/bolt-cli"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: "<1.0.0"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # bolt-boost: breaking major and pre v1 updates
  - package-ecosystem: "cargo"
    directory: "/bolt-boost"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: ">=1.0.0"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # bolt-boost: non-breaking minor and patch updates
  - package-ecosystem: "cargo"
    directory: "/bolt-boost"
    labels:
      - "T: security"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        versions: "<1.0.0"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"