use clap::Parser;
use eyre::Result;

/// CLI command definitions and options.
mod cli;
use cli::{Commands, Opts};

/// CLI command implementations.
mod commands;

/// Shared utility functions and helpers for the CLI.
mod common;

/// Protocol Buffers definitions generated by `prost`.
mod pb;

#[tokio::main]
async fn main() -> Result<()> {
    let _ = dotenvy::dotenv();
    let _ = tracing_subscriber::fmt::try_init();
    let _ = rustls::crypto::ring::default_provider().install_default();

    let cli = Opts::parse();

    match cli.command {
        Commands::Delegate(cmd) => cmd.run().await?,
        Commands::Pubkeys(cmd) => cmd.run().await?,
        Commands::Send(cmd) => cmd.run().await?,
    }

    Ok(())
}
