name: Security Audit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths: 
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    branches:
      - main
      - unstable
    paths: 
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'

permissions:
  issues: write
  checks: write
  pull-requests: read
  contents: read

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}